const ACCEPTED_LANGUAGE = [ 
    'and', 
    'because', 
    'currently',
    'down',
    'elsewhere',
    'finally',
    'good',
    'however',
    'in',
    'joyful',
    'kind',
    'later',
    'marvelous',
    'now',
    'often',
    'peace',
    'quick',
    'rather',
    'some',
    'then',
    'undoubtedly',
    'very',
    'well',
    'xerically',
    'young',
    'zigzag',
]

const ACCEPTED_LANGUAGE_OBJ = {
    a: ['and'],
    b: ['because'],
    c: ['currently'],
    d: ['down'],
    e: ['elsewhere'],
    f: ['finally'],
    g: ['good'],
    h: ['however'],
    i: ['in'],
    j: ['joyful'],
    k: ['kind'],
    l: ['later'],
    m: ['marvelous'],
    n: ['now'],
    o: ['often'],
    p: ['peace'],
    q: ['quick'],
    r: ['rather'],
    s: ['some'],
    t: ['then'],
    u: ['undoubtedly'],
    v: ['very'],
    w: ['well'],
    x: ['xerically'],
    y: ['young'],
    z: ['zigzag'],

}

module.exports = ACCEPTED_LANGUAGE_OBJ